django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from joblist.sitemap import StaticViewsSiteMap,PostViewsSiteMpa
from django.contrib.sitemaps.views import sitemap


sitemaps ={
    'static':StaticViewsSiteMap,
    'post': PostViewsSiteMpa
}

urlpatterns = [
    # path('', include('joblist.urls')),
    path('sitemap.xml',sitemap,{'sitemaps': sitemaps}),
    path('admin/', admin.site.urls),
    path('register', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('', include('joblist.urls')),
    path('login/', auth_views.LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="users/logout.html"), name='logout'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='users/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"), name='password_reset'),


    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

joblist/urls.py
from django.urls import path
from . import views
from .views import PostListView,PostDetailView,PostCreateView,PostUpdateView,PostDeleteView,UserPostListView



urlpatterns = [
    path('', PostListView.as_view(), name='joblist-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='joblist-about'),
    
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image= models.ImageField(default='default.jpg',upload_to="profile_pics")
    about_company=models.TextField()
    company_name =models.CharField(max_length=100)

    def __str__(self):
        return f'{self.user.username} Profile'
        
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()


    class Meta:
        model = User
        fields = ['username', 'email','password1', 'password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()


    class Meta:
        model = User
        fields = ['email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image','company_name','about_company']

users/views.py
from django.shortcuts import render,redirect
# from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import UserRegisterForm,UserUpdateForm ,ProfileUpdateForm
from django.contrib.auth.decorators import login_required
# Create your views here.

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Your account has been created for {username} !')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html',{'form':form})
    

@login_required
def profile(request):

    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request,f'Your profile has been updates !')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form' :u_form,
        'p_form' :p_form
    }
    return render(request, 'users/company_profile.html', context)

users/templates/users/company_profile.html
{% extends "joblist/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.profile.company_name }}</h2>
          <!-- <a class="account-heading" href="{{ user.profile.user }}">{{ user.profile.user }}</a> -->
          <!-- <p class="text-secondary">{{ user.email }}</p> -->
          {% comment %}     <a class="nav-item nav-link"  href="{% url 'user-posts' object.author.username %}">Your Post</a> {% endcomment %}
        </div>
      </div>
      <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Company Info</legend>
              {{ u_form|crispy }}
              {{ p_form|crispy }}
          </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Update</button>
          </div>
      </form>
    </div>
{% endblock content %}

users/templates/users/login.html
{% extends "joblist/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form action="" method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Login</button>
            <a href="{% url 'password_reset' %}" class='ml-2'>Forget Password?</a>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">Need An Account? <a href="{% url 'register' %}" class='ml-2'>Sign Up Now</a></small> <br>
        <!-- <small class="text-muted">Forget Password? <a href="{% url 'password_reset' %}" class='ml-2'>Reset Password</a></small> -->
    </div>
</div>

{% endblock content %}

users/templates/users/logout.html
{% extends "joblist/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<h2>You have been logged out</h2>
   
    <div class="border-top pt-3">
        <small class="text-muted">Already Have An Account? <a href="{% url 'login' %}">Log In Again</a></small>
    </div>


{% endblock content %}

users/templates/users/password_change.html
{% extends "joblist/base.html" %}

{% block content %}
<style type="text/css">
  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
  }

  .form-signin .checkbox {
    font-weight: 400;
  }

  .form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
  }

  .form-signin .form-control:focus {
    z-index: 2;
  }

  .form-signin input[type="password"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }

  .h3 {
    text-align: center;
  }
</style>


<form method="POST" class="form-signin">{% csrf_token %}
  <h1 class="h3 mb-3 font-weight-normal">Reset password</h1>
  <input name="old_password" class="form-control" placeholder="Old password" type="password" id="id_old_password"
    required="true">
  <input name="new_password1" class="form-control" placeholder="New password" type="password" id="id_new_password1"
    required="true">
  <input name="new_password2" class="form-control" placeholder="Confirm password" type="password" id="id_new_password2"
    required="true">

  {% for field in form %}
  {% for error in field.errors %}
  <p style="color: red">{{ error }}</p>
  {% endfor %}
  {% endfor %}

  <button class="btn btn-lg btn-primary btn-block" type="submit">Reset</button>
</form>



{% endblock content %}

users/templates/users/password_change_done.html
{% extends "joblist/base.html" %}

{% block content %}

<div class="container">
	<div class="d-flex flex-column">
		<p class="m-auto">Your password has been updated
		</p>
	</div>
</div>

{% endblock content %}

users/templates/users/password_reset.html
{% extends "joblist/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form action="" method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Request Password Reset</button>
        </div>
    </form>
    
</div>

{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends "joblist/base.html" %}


{% block content %}

<div class="container">
	<div class="d-flex flex-column">
		<p class="m-auto">Your password has been reset. You may go ahead and <a href="{% url 'login' %}">sign in</a>
			now.</p>
	</div>
</div>

{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends "joblist/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Reset Password</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/password_reset_done.html
{% extends "joblist/base.html" %}

{% block content %}

<div class="container">

	<div class="d-flex flex-column">
		<p class="m-auto p-2">
			We've emailed you instructions for setting your password, if an account exists with the email you entered.
			You should receive them shortly.
		</p>
		<p class="m-auto p-2">
			If you don't receive an email, please make sure you've entered the address you registered with,
			and check your spam folder.
		</p>
		<p class="m-auto p-2"><a href="{% url 'joblist-home' %}">Return to home page</a></p>
	</div>
</div>

{% endblock content %} 

users/templates/users/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your account {{ user.email }} with phone number {{ user.phone}} ,
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
Ecroad Team
{% endautoescape content %}

users/templates/users/password_reset_form.html
{% extends "joblist/base.html" %}


{% block content %}

<style type="text/css">
  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
  }

  .form-signin .checkbox {
    font-weight: 400;
  }

  .form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
  }

  .form-signin .form-control:focus {
    z-index: 2;
  }

  .form-signin input[type="email"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }

  .h3 {
    text-align: center;
  }
</style>


<form method="POST" class="form-signin">{% csrf_token %}
  <h1 class="h3 mb-3 font-weight-normal">Reset password</h1>
  <input name="email" class="form-control" placeholder="Email address" type="email" id="id_email" required="true">
  <button class="btn btn-lg btn-primary btn-block" type="submit">Send reset email</button>
</form>



{% endblock content %}

users/templates/users/register.html
{% extends "joblist/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form action="" method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today

                
            </legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Sign Up</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">Already Have An Account? <a  href="{% url 'login' %}" class='ml-2'>Sign In</a></small>
    </div>
</div>

{% endblock content %}